#!/usr/bin/env python3
"""Build six expressions per companion from identity-grounded alpha sheets.

The source sheet is a 3x2 grid in row-major order. Each cell is cropped to
the visible alpha content, resized with premultiplied alpha, right-aligned in
one shared canvas, and written both as a WebP file and as an inlined data URI.
The generated module is pure standard library at runtime.
"""

from __future__ import annotations

import argparse
import base64
import io
from pathlib import Path

import numpy as np
from PIL import Image

SCRIPT_DIR = Path(__file__).resolve().parent
PLUGIN_DIR = SCRIPT_DIR.parent
SOURCE_DIR = PLUGIN_DIR / "assets" / "companions"
SKINS = ("cat", "candy", "corgi", "mint", "frost", "tea")
OUTPUT_DIR = PLUGIN_DIR / "assets" / "companions" / "expressions"
GENERATED_MODULE = "companion_expressions.py"

EXPRESSION_ORDER = ("idle", "happy", "concerned", "notice", "waiting", "pet")
GRID_COLUMNS = 3
GRID_ROWS = 2
RUNTIME_HEIGHT = 384
WEBP_QUALITY = 90

# The generated sheet has a soft alpha glow whose barely visible values reach
# the cell border. Ignore that fringe when finding the character box; the
# actual soft edge inside the box is retained in the rendered sprite.
ALPHA_CROP_THRESHOLD = 32


def source_cells(image: Image.Image, source_name: str = "sheet") -> list[tuple[str, Image.Image, tuple[int, int, int, int]]]:
    """Return the six row-major cells and their visible alpha boxes."""
    if image.mode != "RGBA":
        raise SystemExit(f"{source_name}: expected RGBA source, got {image.mode}")
    width, height = image.size
    if width % GRID_COLUMNS or height % GRID_ROWS:
        raise SystemExit(
            f"{source_name}: {width}x{height} is not divisible by {GRID_COLUMNS}x{GRID_ROWS}"
        )
    cell_width, cell_height = width // GRID_COLUMNS, height // GRID_ROWS
    cells = []
    for index, name in enumerate(EXPRESSION_ORDER):
        row, column = divmod(index, GRID_COLUMNS)
        cell = image.crop(
            (column * cell_width, row * cell_height,
             (column + 1) * cell_width, (row + 1) * cell_height)
        )
        alpha = cell.getchannel("A")
        low, high = alpha.getextrema()
        if low != 0 or high < 128:
            raise SystemExit(f"{source_name}: expression {name} needs a real transparent background and visible body")
        visible = alpha.point(lambda value: 255 if value >= ALPHA_CROP_THRESHOLD else 0)
        box = visible.getbbox()
        if box is None:
            raise SystemExit(f"{source_name}: expression {name} has no visible alpha")
        cells.append((name, cell, box))
    return cells


def resize_premultiplied(image: Image.Image, size: tuple[int, int]) -> Image.Image:
    """Resize RGBA without pulling backdrop colour through transparent edges."""
    rgba = np.asarray(image.convert("RGBA"), dtype=np.float32)
    alpha = rgba[..., 3] / 255.0
    planes = []
    for index in range(3):
        plane = Image.fromarray(rgba[..., index] * alpha, "F")
        planes.append(np.asarray(plane.resize(size, Image.LANCZOS), dtype=np.float32))
    alpha_small = np.asarray(
        Image.fromarray(alpha * 255.0, "F").resize(size, Image.LANCZOS),
        dtype=np.float32,
    ) / 255.0
    safe = np.clip(alpha_small, 1e-6, 1.0)
    straight = [np.clip(plane / safe, 0.0, 255.0) for plane in planes]
    pixels = np.dstack([*straight, alpha_small * 255.0]).round().clip(0, 255).astype(np.uint8)
    return Image.fromarray(pixels, "RGBA")


def render_cells(
    cells: list[tuple[str, Image.Image, tuple[int, int, int, int]]], canvas_width: int | None = None
) -> tuple[dict[str, Image.Image], dict[str, tuple[int, int, int, int]]]:
    widths = [max(1, round(RUNTIME_HEIGHT * (box[2]-box[0]) / (box[3]-box[1]))) for _, _, box in cells]
    canvas_width = canvas_width or ((max(widths)+15)//16)*16
    if not 96 <= canvas_width <= 384:
        raise SystemExit(f"Unusable companion aspect ratio: canvas width {canvas_width}")
    rendered: dict[str, Image.Image] = {}
    boxes: dict[str, tuple[int, int, int, int]] = {}
    for name, cell, box in cells:
        cropped = cell.crop(box)
        width = max(1, round(RUNTIME_HEIGHT * cropped.width / cropped.height))
        if width > canvas_width:
            raise SystemExit(
                f"{name}: content width {width}px exceeds shared canvas {canvas_width}px"
            )
        sprite = resize_premultiplied(cropped, (width, RUNTIME_HEIGHT))
        canvas = Image.new("RGBA", (canvas_width, RUNTIME_HEIGHT))
        canvas.alpha_composite(sprite, (canvas_width - width, 0))
        rendered[name] = canvas
        boxes[name] = box
    return rendered, boxes


def encode(image: Image.Image) -> bytes:
    buffer = io.BytesIO()
    image.save(buffer, "WEBP", quality=WEBP_QUALITY, method=6)
    return buffer.getvalue()


def write_module(payloads: dict, metadata: dict) -> None:
    lines = [
        '"""Generated by build_companion_expressions.py; do not edit by hand."""',
        "from __future__ import annotations", "",
        f"RUNTIME_HEIGHT = {RUNTIME_HEIGHT}",
        f"WEBP_QUALITY = {WEBP_QUALITY}",
        f"EXPRESSION_ORDER = {EXPRESSION_ORDER!r}",
        f"SOURCE_METADATA = {metadata!r}",
        "", "COMPANION_EXPRESSIONS = {",
    ]
    for skin, frames in payloads.items():
        lines.append(f"    {skin!r}: {{")
        for name, uri in frames.items():
            lines.append(f"        {name!r}: (")
            for offset in range(0, len(uri), 96):
                lines.append(f"            {uri[offset:offset+96]!r}")
            lines.append("        ),")
        lines.append("    },")
    lines.extend(["}", ""])
    (SCRIPT_DIR / GENERATED_MODULE).write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list", action="store_true", help="validate and report sources only")
    args = parser.parse_args()
    payloads, metadata, outputs = {}, {}, {}
    for skin in SKINS:
        source_path = SOURCE_DIR / f"{skin}-expressions-source.png"
        with Image.open(source_path) as source:
            cells = source_cells(source, str(source_path))
            # Keep the already-approved cat canvas unchanged.
            rendered, boxes = render_cells(cells, 288 if skin == "cat" else None)
            metadata[skin] = {"source_size": source.size, "canvas_size": rendered["idle"].size, "boxes": boxes}
        print(f"{skin}: {metadata[skin]['source_size']} -> {metadata[skin]['canvas_size']}, six RGBA expressions")
        if args.list:
            continue
        payloads[skin] = {}
        for name, image in rendered.items():
            data = encode(image)
            outputs[f"{skin}-{name}.webp"] = data
            payloads[skin][name] = "data:image/webp;base64," + base64.b64encode(data).decode("ascii")
    if not args.list:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        for name, data in outputs.items():
            (OUTPUT_DIR / name).write_bytes(data)
        write_module(payloads, metadata)
        print(f"wrote {len(outputs)} expressions and scripts/{GENERATED_MODULE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
