#!/usr/bin/env python3
"""Build the six deterministic cat-expression sprites from one alpha sheet.

The source sheet is a 3x2 grid in row-major order. Each cell is cropped to
the visible alpha content, resized with premultiplied alpha, right-aligned in
one shared canvas, and written both as a WebP file and as an inlined data URI.
The generated module is pure standard library at runtime.
"""

from __future__ import annotations

import argparse
import base64
import io
from pathlib import Path

import numpy as np
from PIL import Image

SCRIPT_DIR = Path(__file__).resolve().parent
PLUGIN_DIR = SCRIPT_DIR.parent
SOURCE = PLUGIN_DIR / "assets" / "companions" / "cat-expressions-source.png"
OUTPUT_DIR = PLUGIN_DIR / "assets" / "companions" / "expressions"
GENERATED_MODULE = "companion_expressions.py"

EXPRESSION_ORDER = ("idle", "happy", "concerned", "notice", "waiting", "pet")
GRID_COLUMNS = 3
GRID_ROWS = 2
RUNTIME_HEIGHT = 384
CANVAS_WIDTH = 288
WEBP_QUALITY = 90

# The generated sheet has a soft alpha glow whose barely visible values reach
# the cell border. Ignore that fringe when finding the character box; the
# actual soft edge inside the box is retained in the rendered sprite.
ALPHA_CROP_THRESHOLD = 32


def source_cells(image: Image.Image) -> list[tuple[str, Image.Image, tuple[int, int, int, int]]]:
    """Return the six row-major cells and their visible alpha boxes."""
    if image.mode != "RGBA":
        raise SystemExit(f"{SOURCE}: expected RGBA source, got {image.mode}")
    width, height = image.size
    if width % GRID_COLUMNS or height % GRID_ROWS:
        raise SystemExit(
            f"{SOURCE}: {width}x{height} is not divisible by {GRID_COLUMNS}x{GRID_ROWS}"
        )
    cell_width, cell_height = width // GRID_COLUMNS, height // GRID_ROWS
    cells = []
    for index, name in enumerate(EXPRESSION_ORDER):
        row, column = divmod(index, GRID_COLUMNS)
        cell = image.crop(
            (column * cell_width, row * cell_height,
             (column + 1) * cell_width, (row + 1) * cell_height)
        )
        alpha = cell.getchannel("A")
        visible = alpha.point(lambda value: 255 if value >= ALPHA_CROP_THRESHOLD else 0)
        box = visible.getbbox()
        if box is None:
            raise SystemExit(f"{SOURCE}: expression {name} has no visible alpha")
        cells.append((name, cell, box))
    return cells


def resize_premultiplied(image: Image.Image, size: tuple[int, int]) -> Image.Image:
    """Resize RGBA without pulling backdrop colour through transparent edges."""
    rgba = np.asarray(image.convert("RGBA"), dtype=np.float32)
    alpha = rgba[..., 3] / 255.0
    planes = []
    for index in range(3):
        plane = Image.fromarray(rgba[..., index] * alpha, "F")
        planes.append(np.asarray(plane.resize(size, Image.LANCZOS), dtype=np.float32))
    alpha_small = np.asarray(
        Image.fromarray(alpha * 255.0, "F").resize(size, Image.LANCZOS),
        dtype=np.float32,
    ) / 255.0
    safe = np.clip(alpha_small, 1e-6, 1.0)
    straight = [np.clip(plane / safe, 0.0, 255.0) for plane in planes]
    pixels = np.dstack([*straight, alpha_small * 255.0]).round().clip(0, 255).astype(np.uint8)
    return Image.fromarray(pixels, "RGBA")


def render_cells(
    cells: list[tuple[str, Image.Image, tuple[int, int, int, int]]]
) -> tuple[dict[str, Image.Image], dict[str, tuple[int, int, int, int]]]:
    rendered: dict[str, Image.Image] = {}
    boxes: dict[str, tuple[int, int, int, int]] = {}
    for name, cell, box in cells:
        cropped = cell.crop(box)
        width = max(1, round(RUNTIME_HEIGHT * cropped.width / cropped.height))
        if width > CANVAS_WIDTH:
            raise SystemExit(
                f"{name}: content width {width}px exceeds shared canvas {CANVAS_WIDTH}px"
            )
        sprite = resize_premultiplied(cropped, (width, RUNTIME_HEIGHT))
        canvas = Image.new("RGBA", (CANVAS_WIDTH, RUNTIME_HEIGHT))
        canvas.alpha_composite(sprite, (CANVAS_WIDTH - width, 0))
        rendered[name] = canvas
        boxes[name] = box
    return rendered, boxes


def encode(image: Image.Image) -> bytes:
    buffer = io.BytesIO()
    image.save(buffer, "WEBP", quality=WEBP_QUALITY, method=6)
    return buffer.getvalue()


def write_module(payloads: dict[str, str], boxes: dict[str, tuple[int, int, int, int]], source_size: tuple[int, int]) -> None:
    lines = [
        '"""Generated by scripts/build_companion_expressions.py. Do not edit by hand.',
        "",
        "Runtime cat-expression artwork, inlined as data URIs for the overlay.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f"RUNTIME_HEIGHT = {RUNTIME_HEIGHT}",
        f"CANVAS_WIDTH = {CANVAS_WIDTH}",
        f"WEBP_QUALITY = {WEBP_QUALITY}",
        f"SOURCE_SIZE: tuple[int, int] = {source_size}",
        f"SOURCE_GRID: tuple[int, int] = ({GRID_COLUMNS}, {GRID_ROWS})",
        f"EXPRESSION_ORDER: tuple[str, ...] = {EXPRESSION_ORDER!r}",
        "SOURCE_BOXES: dict[str, tuple[int, int, int, int]] = {",
    ]
    for name in EXPRESSION_ORDER:
        lines.append(f'    "{name}": {boxes[name]},')
    lines += [
        "}",
        "",
        "COMPANION_EXPRESSIONS: dict[str, dict[str, str]] = {",
        '    "cat": {',
    ]
    for name in EXPRESSION_ORDER:
        chunk = payloads[name]
        lines.append(f'        "{name}": (')
        for index in range(0, len(chunk), 96):
            lines.append(f'            "{chunk[index:index + 96]}"')
        lines.append("        ),")
    lines += ["    },", "}", ""]
    (SCRIPT_DIR / GENERATED_MODULE).write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list", action="store_true", help="report the source and stop")
    args = parser.parse_args()
    if not SOURCE.exists():
        print(f"missing source: {SOURCE}")
        return 1
    with Image.open(SOURCE) as source:
        source = source.convert("RGBA")
        cells = source_cells(source)
        if args.list:
            print(f"source: {SOURCE} {source.size} {source.mode}")
            for name, _, box in cells:
                print(f"  {name:9s} <- {box}")
            return 0
        rendered, boxes = render_cells(cells)
        source_size = source.size

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    payloads: dict[str, str] = {}
    print(f"source: {SOURCE} {source_size[0]}x{source_size[1]}")
    print(f"canvas: {CANVAS_WIDTH}x{RUNTIME_HEIGHT}px, webp q{WEBP_QUALITY}")
    for name in EXPRESSION_ORDER:
        data = encode(rendered[name])
        (OUTPUT_DIR / f"cat-{name}.webp").write_bytes(data)
        payloads[name] = "data:image/webp;base64," + base64.b64encode(data).decode("ascii")
        print(f"  {name:9s} {len(data) / 1024:5.1f} KB -> expressions/cat-{name}.webp")
    write_module(payloads, boxes, source_size)
    print(f"wrote scripts/{GENERATED_MODULE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
