const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const assistant = '[data-content-search-assistant-turn-key]';
const chat = '[data-chatgpt-conversation-turn="true"]';
const root = '#codex-context-token-inspector-root';
const turnSelector = `${assistant}, ${chat}`;
const turn = {closest: selector => selector === turnSelector ? turn : null};
const child = {closest: selector => selector === turnSelector ? turn : null};
const own = {closest: selector => selector === turnSelector || selector === root ? own : null};
const fallback = {closest: selector => selector === turnSelector ? fallback : null};
let rows = {[assistant]: [child, turn, own]};
const context = vm.createContext({document: {querySelectorAll: selector => rows[selector] || []}});
vm.runInContext("const ROOT_ID = 'codex-context-token-inspector-root'", context);
vm.runInContext(fs.readFileSync(path.join(__dirname, '../quota_monitor/panel_host_details.js'), 'utf8'), context);
assert.deepEqual(Array.from(context.hostMessageNodes()), [turn]);
rows = {[chat]: [fallback]};
assert.deepEqual(Array.from(context.hostMessageNodes()), [fallback]);
rows = {};
assert.deepEqual(Array.from(context.hostMessageNodes()), []);
const tagged = {dataset: {appActionSidebarThreadId: 'thread-1'}};
assert.equal(context.hostThreadId({matches: () => true, dataset: tagged.dataset}), 'thread-1');
assert.equal(context.hostThreadId({matches: () => false, querySelector: () => tagged}), 'thread-1');
assert.equal(context.hostThreadId({matches: () => false, querySelector: () => null}), null);
const messages = [{textContent: ' first answer '}, {textContent: 'second answer'}];
const details = [{textPrefix: 'first', id: 1}, {textPrefix: 'second', id: 2}];
assert.deepEqual(Array.from(context.hostAssignments(messages, details), item => item.id), [1, 2]);
assert.deepEqual(Array.from(context.hostAssignments([{textContent: 'unknown'}], details), item => item.id), [2]);
console.log('host message selection: deduplication, fallback and own-root exclusion passed');
