const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('playwright');
const source=fs.readFileSync(path.join(__dirname,'../quota_monitor/panel_disclosures.js'),'utf8');
(async()=>{for(const engine of [chromium,webkit]){const browser=await engine.launch();try{
 const page=await browser.newPage();
 await page.setContent('<main></main>');
 await page.evaluate(source=>{
  window.SKINS_OPEN_KEY='skins';window.values={'cti-details-open':'true',skins:'invalid'};window.writes=[];
  Object.defineProperty(window,'localStorage',{value:{getItem:key=>{if(window.failRead)throw Error('denied');return values[key];},setItem:(key,value)=>{if(window.failWrite)throw Error('full');writes.push([key,value]);values[key]=value;}}});
  window.clampHud=()=>{window.clamps=(window.clamps||0)+1;};
  (0,eval)(source);
  window.root=document.querySelector('main');
  root.addEventListener('toggle',event=>handleDisclosureToggle(root,event),true);
  window.rebuild=()=>{const template=document.createElement('template');template.innerHTML='<details data-details><summary>Details</summary></details><details data-skins><summary>Skins</summary></details>';restoreDisclosures(template.content,root);root.replaceChildren(template.content);};
  rebuild();
 },source);
 await page.waitForTimeout(30);
 assert.equal(await page.locator('[data-details]').evaluate(n=>n.open),true);
 assert.equal(await page.locator('[data-skins]').evaluate(n=>n.open),false);
 assert.deepEqual(await page.evaluate(()=>writes),[],'initialization must not write preferences');
 await page.evaluate(()=>{window.failWrite=true;});
 await page.locator('[data-details] summary').click();
 await page.waitForFunction(()=>window.clamps===1);
 await page.evaluate(()=>{window.detached=document.querySelector('[data-details]');rebuild();});
 assert.equal(await page.locator('[data-details]').evaluate(n=>n.open),false);
 await page.evaluate(()=>{window.failWrite=false;detached.open=true;detached.dispatchEvent(new Event('toggle'));});
 assert.deepEqual(await page.evaluate(()=>writes),[]);
 await page.locator('[data-skins] summary').click();
 await page.waitForFunction(()=>writes.length===1);
 assert.deepEqual(await page.evaluate(()=>writes),[['skins','true']]);
 await page.evaluate(()=>{rebuild();});
 await page.waitForTimeout(30);
 assert.equal(await page.locator('[data-skins]').evaluate(n=>n.open),true);
 assert.equal(await page.evaluate(()=>writes.length),1);
 await page.evaluate(()=>{root.replaceChildren();window.failRead=true;rebuild();});
 assert.equal(await page.locator('[data-details]').evaluate(n=>n.open),false);
 assert.equal(await page.locator('[data-skins]').evaluate(n=>n.open),false);
 console.log(engine.name()+': defaults, no initialization writes, failed persistence, rebuild, detached events and read failure passed');
}finally{await browser.close();}}})().catch(error=>{console.error(error);process.exitCode=1;});
